[package]
name = "star-aligner"
version = "0.1.0"
authors = ["Kai Zhang <zhangkai33@westlake.edu.cn>"]
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1"
libc = "*"
noodles = { version = "0.80", features = ["core", "fastq", "bam", "sam"] }
star-sys = { version = "0.2", workspace = true}

[profile.release]
debug = 1